#!/usr/bin/env python
"""Generate Appendix A of the project's working notes: full per-cell tables for every method tried
since 7 August, straight from the results CSVs (no hand-copied numbers).

For FREE methods the per-dataset curve IS the full grid (rung-invariant, stated per table).
For multi-parameter grids the complete hypercube lives in the named CSV; the tables here show the
per-cell values at the headline / pre-committed parameter, which is the honest cross-section.

    python scripts/checks/gen_appendix.py > /tmp/appendix.md   (or --out)
"""
import csv as _csv
import glob
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / "results"
SLUG = "meta-llama_Meta-Llama-3.1-8B"
LONG = ["pubmed_qa", "med_quad", "asqa", "xsum", "cnn_dailymail", "samsum", "expertqa", "factscore"]
RUNGS = ["ID", "SameTask-long", "DiffTask-long", "LOO-long", "1ds-Diff-long"]
OOD = RUNGS[1:]


def emit(title, note, header, rows):
    print(f"\n### {title}\n")
    if note:
        print(note + "\n")
    print("| " + " | ".join(header) + " |")
    print("|" + "---|" * len(header))
    for r in rows:
        print("| " + " | ".join(r) + " |")


def f(x):
    return f"{x:+.3f}" if x is not None and np.isfinite(x) else "—"


def main():
    print("## Appendix A — full per-cell tables for every method tried since 7 August")
    print(f"\n> Generated by `scripts/checks/gen_appendix.py` from the results CSVs; regenerate rather")
    print("> than edit. Population throughout: widened `cells_long`, `meta-llama/Llama-3.1-8B`,")
    print("> legacy carve, judge label, 3 seeds for trained methods. Free methods are RUNG-INVARIANT,")
    print("> so their per-dataset table covers ID and all four OOD rungs at once.")

    # ---- A1: the four free sharpening families ----
    fam = defaultdict(lambda: defaultdict(dict))
    p1 = RES / f"sharpening_family__{SLUG}__round2.csv"
    if p1.exists():
        for r in _csv.DictReader(open(p1)):
            if r["family"] in ("softmax_tau", "power_p", "lehmer_beta", "rank_tau"):
                fam[r["family"]][r["dataset"]][r["param"]] = float(r["prr"])
        for name, label in [("softmax_tau", "softmax-τ (W1)"), ("power_p", "power mean (W1)"),
                            ("lehmer_beta", "Lehmer-β (W1/W4)"), ("rank_tau", "rank-τ (W4 Q-D)")]:
            ds = fam[name]
            if not ds:
                continue
            params = sorted({p for d in ds.values() for p in d},
                            key=lambda x: (x == "inf", float(x) if x != "inf" else 0))
            rows = [[d] + [f(ds[d].get(p)) for p in params] for d in LONG if d in ds]
            rows.append(["**mean**"] + [f(float(np.mean([ds[d][p] for d in LONG if d in ds])))
                                        for p in params])
            emit(f"A1 — {label}: PRR per dataset × parameter",
                 f"FREE method → rung-invariant. Source: `{p1.name}`. Endpoints: first param = "
                 "`perplexity`'s ranking, `inf` = `msp_min`'s.",
                 ["eval"] + params, rows)

    # ---- A2: length-conditioned tau (W1b) ----
    p2 = RES / f"sharpening_family__{SLUG}__lengthtau.csv"
    if p2.exists():
        lt = defaultdict(dict)
        for r in _csv.DictReader(open(p2)):
            if r["family"] == "length_tau":
                lt[r["dataset"]][r["param"]] = float(r["prr"])
        params = sorted({p for d in lt.values() for p in d})
        rows = [[d] + [f(lt[d].get(p)) for p in params] for d in LONG if d in lt]
        emit("A2 — length-conditioned τ (W1b, exploratory)",
             f"FREE → rung-invariant. `t<τ0>_g<γ>`; γ=0 columns reproduce A1's softmax-τ exactly. "
             f"Source: `{p2.name}`. γ=0 won every column mean (§3.8).",
             ["eval"] + params, rows)

    # ---- A3: Track 2 temperature grid (5/8 evals) ----
    t2 = defaultdict(dict)
    for fpath in glob.glob(str(RES / f"sharpening_wmsp_*__{SLUG}.csv")):
        if "SMOKE" in fpath or "verdict" in fpath:
            continue
        for r in _csv.DictReader(open(fpath)):
            if r.get("kind", "").startswith("floor"):
                continue
            try:
                t2[(r["rung"], r["eval"])][(float(r["T0"]), float(r["gamma"]))] = float(r["prr"])
            except (ValueError, TypeError, KeyError):
                continue
    if t2:
        rows = []
        for e in LONG:
            for rg in RUNGS:
                c = t2.get((rg, e))
                if not c:
                    continue
                noop = c.get((1.0, 0.0))
                bk = max(c, key=c.get)
                rows.append([f"{e}/{rg.replace('-long','')}", f(noop), f(c[bk]),
                             f"T0={bk[0]:g}, γ={bk[1]:g}"])
        emit("A3 — Track 2: temperature on the learned weighter (PARTIAL, 5/8 evals — "
             "samsum/expertqa/factscore cancelled, §4)",
             "Per cell: the no-op (≡ `wMSP-norm`, matches `pdl_master` to 4 dp) and the per-cell "
             "grid best (**ORACLE, not a result**). Full 25-point grids: "
             "`sharpening_wmsp_<eval>__…csv`.",
             ["cell", "no-op (T0=1, γ=0)", "grid best (ORACLE)", "at"], rows)

    # ---- A4: mask ablation, per-cell unmasked − masked ----
    mk = defaultdict(dict)
    for fpath in glob.glob(str(RES / f"mask_ablation_*__{SLUG}.csv")):
        if "SMOKE" in fpath or "verdict" in fpath:
            continue
        for r in _csv.DictReader(open(fpath)):
            if r["variant"] == "floor":
                continue
            mk[(r["variant"], r["mode"])][(r["rung"], r["eval"])] = float(r["prr"])
    for v in ["norm", "shrink2", "shrink10"]:
        if (v, "masked") not in mk:
            continue
        rows = []
        for e in LONG:
            vals = []
            for rg in RUNGS:
                a = mk[(v, "masked")].get((rg, e))
                b = mk[(v, "unmasked")].get((rg, e))
                vals.append(f(b - a) if a is not None and b is not None else "—")
            rows.append([e] + vals)
        emit(f"A4 — mask ablation, wMSP-{v}: (unmasked − masked) per cell",
             "Complete 8×5, 3 seeds. Masked arms ≡ `pdl_master` to 4 dp. All-null verdict in §14. "
             f"Source: `mask_ablation_<eval>__…csv`.",
             ["eval"] + [r.replace("-long", "") for r in RUNGS], rows)

    # ---- A5: NLL tilts (W5 Q-C), OOD means per dataset × parameter ----
    tl = defaultdict(lambda: defaultdict(dict))
    for fpath in glob.glob(str(RES / f"sharpening_lambda_*__{SLUG}.csv")):
        if "SMOKE" in fpath or "verdict" in fpath:
            continue
        for r in _csv.DictReader(open(fpath)):
            if r["kind"] in ("tilt_exp", "tilt_pow"):
                tl[r["kind"]][r["eval"]].setdefault(r["param"], {})[r["rung"]] = float(r["prr"])
    for kind, label in [("tilt_exp", "exponential tilt τ·z(nll)"), ("tilt_pow", "power tilt β·log nll")]:
        ds = tl[kind]
        if not ds:
            continue
        params = sorted({p for d in ds.values() for p in d},
                        key=lambda x: (x == "inf", float(x) if x != "inf" else 0))
        rows = []
        for e in LONG:
            if e not in ds:
                continue
            vals = []
            for p in params:
                rr = ds[e].get(p, {})
                v = [rr.get(rg) for rg in OOD]
                vals.append(f(float(np.mean(v))) if all(x is not None for x in v) else "—")
            rows.append([e] + vals)
        emit(f"A5 — W5 Q-C, {label}: OOD mean per dataset × parameter",
             "EXPLORATORY (no pre-committed parameter; per-cell best is an ORACLE). τ/β=0 ≡ "
             "`wMSP-norm`; `inf` ≡ the content-token floor. Per-cell values: "
             "`sharpening_lambda_<eval>__…csv`.",
             ["eval"] + params, rows)

    # ---- A6: F5b anchored wMSP, per cell at λ=10 with the random control ----
    anc, rnd = defaultdict(dict), defaultdict(dict)
    for fpath in glob.glob(str(RES / f"anchor_msp_min_*__logpen__{SLUG}.csv")):
        if "SMOKE" in fpath:
            continue
        for r in _csv.DictReader(open(fpath)):
            if r["mode"] == "anchor":
                anc[(r["rung"], r["eval"])][float(r["lambda"])] = float(r["prr"])
            elif r["mode"] == "random":
                rnd[(r["rung"], r["eval"])][float(r["lambda"])] = float(r["prr"])
    if anc:
        rows = []
        for e in LONG:
            v0, v10, d10 = [], [], []
            for rg in RUNGS:
                c = anc.get((rg, e), {})
                r10 = rnd.get((rg, e), {}).get(10.0)
                v0.append(f(c.get(0.0)))
                v10.append(f(c.get(10.0)))
                d10.append(f(c.get(10.0) - r10) if c.get(10.0) is not None and r10 is not None else "—")
            rows.append([e] + v0 + v10 + d10)
        hdr = (["eval"] + [f"λ0 {r.replace('-long','')}" for r in RUNGS]
               + [f"λ10 {r.replace('-long','')}" for r in RUNGS]
               + [f"a−r {r.replace('-long','')}" for r in RUNGS])
        emit("A6 — F5b anchored wMSP (log penalty): per cell, λ=0 vs λ=10 vs (anchor − random)@λ=10",
             "The penalty BITES only on pubmed_qa/xsum/cnn_dailymail (§16.2); other rows are "
             "UNTESTED, not null. λ=0 ≡ `wMSP-norm` (matches `pdl_master` to 4 dp). Full λ grids and "
             "`p[k]`: `anchor_msp_min_<eval>__logpen__…csv`.",
             hdr, rows)

    print("\n### A7 — where the remaining full grids already live")
    print("""
| method | full table | source CSV |
|---|---|---|
| λ = 1 / 1.5 (W5) | §15.2b, complete 8×5 per cell | `sharpening_lambda_<eval>__…csv` |
| Lehmer curve + per-dataset significance | §7.1c | `sharpening_family__…__round2.csv` |
| F5 linear (stall record) | §16.1 (`p[k]` table) | `anchor_msp_min_<eval>__…csv` |
| oracle retractions | §8 | `oracle_shuffle_audit__…csv` |
| orthogonality / seed reliability | §9 | `orthogonality_map__…csv` |
| regime map / F3 identifiability | §10 | `regime_map__…csv` |
| special tokens / EOS provenance | §12 / §13 | `special_token_audit__…csv`, `eos_provenance__…csv` |
""")


if __name__ == "__main__":
    main()
