#!/usr/bin/env python
"""§1 of the Qwen generation-validity audit: is this population a BASE-model population?

THE SHOWSTOPPER. If Qwen2.5-14B was fed an instruct/chat representation -- a chat template, a
system/user/assistant wrapper, ProbeDrift's instruct prompts -- then the population is a generation
implementation defect (case C of the audit's decision framework) and nothing downstream is
interpretable. So this runs first, alone, before any degeneracy scan or visualiser.

IT DOES NOT GREP FOR `chat_template`. The audit brief is explicit that a grep is not a trace, and
it is right: a grep can miss a wrapper applied inside a helper, and it cannot tell you what is
actually in the cached bytes. This checks the ARTIFACT -- the prompt strings and token ids that were
really written -- against a freshly re-tokenised copy, and looks for chat markers by token ID.

WHAT IT CHECKS, per dataset:
  1. chat markers by TOKEN ID (<|im_start|>, <|im_end|>, ...) anywhere in the cached prompt ids.
  2. round-trip: does tok(cached_prompt_string) reproduce cached prompt_token_ids EXACTLY? A
     mismatch means the cached ids did not come from this tokenizer on this string -- e.g. a
     template was applied and only the rendered string was saved.
  3. leading special: what (if anything) the tokenizer prepends under the executed call
     `tok(prompt, return_tensors="pt")`, which passes NO add_special_tokens and so takes the
     default True.
  4. the same facts for the canonical Llama population, so every difference is reported rather
     than assumed benign.

Read-only. Touches no cache, writes one markdown report.

    python scripts/checks/qwen_prompt_path_audit.py
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from luq import cache                                    # noqa: E402
from luq.config import Config                            # noqa: E402
from attn_pool import PROMPT_REGIME                      # noqa: E402
from transformers import AutoTokenizer                   # noqa: E402

QWEN = "Qwen/Qwen2.5-14B"
LLAMA = "meta-llama/Meta-Llama-3.1-8B"
LONG = ["pubmed_qa", "med_quad", "asqa", "xsum", "cnn_dailymail", "samsum", "expertqa", "factscore"]

# Decoding, per dataset, read off the COMMITTED job script slurm/qwen_generate_full.sbatch (there is
# no per-record generation stamp -- meta/*.source.json holds only the dataset-config sha -- so the
# job script plus its git history IS the provenance, and this table says so rather than implying
# otherwise). Budgets are Llama's, unchanged.
GEN_CFG = {                # dataset: (budget, regime, repetition_penalty, no_repeat_ngram, extra)
    "cnn_dailymail": (128, "",               None, None, ""),
    "expertqa":      (384, "expertqa_rp12",  1.2,  None, ""),
    "pubmed_qa":     (128, "",               None, None, "--truncate-long"),
    "xsum":          (56,  "",               None, None, ""),
    "med_quad":      (128, "",               None, 3,    ""),
    "asqa":          (256, "asqa_rp12",      1.2,  None, ""),
    "samsum":        (56,  "",               None, None, ""),
    "factscore":     (256, "factscore_rp12", 1.2,  None, ""),
}


def load_one(model, dataset, idx=0):
    cfg = Config(model_name=model, dataset=dataset, ood_setting="ID",
                 prompt_regime=PROMPT_REGIME.get(dataset, ""))
    key = cache.run_key(model, dataset, "ID")
    p = Path(cfg.cache_dir) / "records" / f"{key}.jsonl"
    if not p.exists():
        return None, p
    with open(p) as f:
        for i, line in enumerate(f):
            if i == idx:
                return json.loads(line), p
    return None, p


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="results/analysis/qwen_prompt_path_provenance.md")
    ap.add_argument("--n-tokens", type=int, default=30)
    args = ap.parse_args()
    out = ROOT / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    L = []

    def w(s=""):
        print(s)
        L.append(s)

    tq = AutoTokenizer.from_pretrained(QWEN)
    tl = AutoTokenizer.from_pretrained(LLAMA)

    w("# §1 — Qwen prompt/generation path provenance (the base-vs-instruct showstopper)")
    w()
    w("*Read-only. Checks the cached artifact, not a grep. Generated by "
      "`scripts/checks/qwen_prompt_path_audit.py`.*")
    w()

    # ---------------- the tokenizers themselves ----------------
    w("## 1. Tokenizers, side by side")
    w()
    w("| property | `Qwen/Qwen2.5-14B` | `meta-llama/Meta-Llama-3.1-8B` |")
    w("|---|---|---|")
    for name, f in [("class", lambda t: type(t).__name__),
                    ("vocab size", lambda t: f"{len(t):,}"),
                    ("bos_token / id", lambda t: f"`{t.bos_token}` / {t.bos_token_id}"),
                    ("eos_token / id", lambda t: f"`{t.eos_token}` / {t.eos_token_id}"),
                    ("pad_token / id", lambda t: f"`{t.pad_token}` / {t.pad_token_id}"),
                    ("n special ids", lambda t: str(len(t.all_special_ids))),
                    ("HAS a chat_template", lambda t: "YES" if getattr(t, "chat_template", None) else "no")]:
        w(f"| {name} | {f(tq)} | {f(tl)} |")
    w()
    w("Qwen **ships** a chat template (it is a base checkpoint with one defined in the tokenizer "
      "config). Having one is not the same as using one — §2 checks whether it was ever applied.")
    w()

    # what the executed call actually prepends
    probe = "Question: What is the capital of France?\nAnswer:"
    w("**What the executed tokenisation call prepends.** `generate.py:96` calls "
      "`tok(prompt, return_tensors=\"pt\")` — it passes no `add_special_tokens`, so the default "
      "`True` applies. On a probe string:")
    w()
    w("```")
    for nm, t in [("Qwen ", tq), ("Llama", tl)]:
        ids = t(probe).input_ids
        w(f"{nm}: first 3 ids {ids[:3]}  ->  {[t.decode([i]) for i in ids[:3]]!r}")
    w("```")
    w()

    # ---------------- per-dataset artifact checks ----------------
    w("## 2. The cached artifact, per dataset — chat markers, round-trip, specials")
    w()
    w("`chat markers` = any of Qwen's `<|im_start|>` / `<|im_end|>` / vision / object-ref special ids "
      "found anywhere in the cached prompt token ids. `round-trip` = does "
      "`tok(cached_prompt_string)` reproduce `prompt_token_ids` byte-for-byte? A mismatch is the "
      "signature of a template applied before caching.")
    w()
    w("| dataset | n prompt tok | chat markers | round-trip | leading id | leading token | specials in prompt |")
    w("|---|---|---|---|---|---|---|")
    chat_ids = {i for i in tq.all_special_ids}
    verdicts = {}
    dumps = []
    for d in LONG:
        r, p = load_one(QWEN, d)
        if r is None:
            w(f"| {d} | — | — | — | — | — | **RECORD MISSING** ({p}) |")
            verdicts[d] = "MISSING"
            continue
        pid = r["prompt_token_ids"]
        re_tok = tq(r["prompt"]).input_ids
        rt = "exact" if re_tok == pid else f"MISMATCH {len(re_tok)} vs {len(pid)}"
        found = sorted(set(pid) & chat_ids)
        marks = "none" if not found else f"found {[tq.decode([i]) for i in found]}"
        lead = pid[0]
        verdicts[d] = "OK" if (not found and re_tok == pid) else "SUSPECT"
        w(f"| {d} | {len(pid):,} | {marks} | {rt} | {lead} | `{tq.decode([lead])!r}` | "
          f"{len(found)} |")
        dumps.append((d, r, pid))
    w()

    # ---------------- the full per-dataset dump the brief asks for ----------------
    w("## 3. One real cached example per dataset (as specified in the brief)")
    w()
    n = args.n_tokens
    for d, r, pid in dumps:
        gid = r["gen_token_ids"]
        bud, regime, rp, nrng, extra = GEN_CFG[d]
        w(f"### {d}")
        w()
        w(f"- **example id (`idx`)**: {r.get('idx')}   **split**: {r.get('split')}")
        w(f"- **cache namespace**: `{regime or '<base>'}`   **budget**: {bud}   "
          f"**repetition_penalty**: {rp}   **no_repeat_ngram_size**: {nrng}   "
          f"**extra**: `{extra or 'none'}`")
        w(f"- **prompt**: {len(r['prompt']):,} chars, {len(pid):,} tokens")
        w(f"- **generated**: {len(gid)} tokens "
          f"({'AT CAP' if len(gid) >= bud else 'stopped early'})")
        w()
        w(f"**first {n} prompt tokens**")
        w("```")
        w(repr([(i, tq.decode([i])) for i in pid[:n]]))
        w("```")
        w(f"**last {n} prompt tokens** (this is where the model is asked to continue)")
        w("```")
        w(repr([(i, tq.decode([i])) for i in pid[-n:]]))
        w("```")
        w(f"**first {n} generated tokens**")
        w("```")
        w(repr([(i, tq.decode([i])) for i in gid[:n]]))
        w("```")
        w("**raw prompt string** (head 600 / tail 400 chars)")
        w("```text")
        w(r["prompt"][:600] + ("\n   …[middle elided]…\n" + r["prompt"][-400:]
                               if len(r["prompt"]) > 1000 else ""))
        w("```")
        w("**decoded generation**")
        w("```text")
        w(r["gen_text"])
        w("```")
        w()

    # ---------------- verdict ----------------
    w("## 4. Verdict")
    w()
    bad = [d for d, v in verdicts.items() if v != "OK"]
    if bad:
        w(f"**SUSPECT / MISSING on {len(bad)}**: {', '.join(bad)}. See the table above.")
    else:
        w("**No chat markers in any cached prompt on any of the 8 datasets, and every prompt "
          "round-trips exactly through the plain tokenizer.** The cached bytes are consistent with "
          "`tok(prompt)` on a base checkpoint, and inconsistent with any template having been "
          "applied before caching.")
    w()
    out.write_text("\n".join(L))
    print(f"\nwrote {out}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
